name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.0.0
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2   # ✅ Evită eroarea WebView pe Android
  webview_flutter_wkwebview: ^3.18.2 # ✅ Pentru compatibilitate cu iOS
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # ✅ Corectată pentru compatibilitate cu versiunea Flutter

flutter:
  uses-material-design: true

  assets:
    - assets/blockly/  # ✅ Asigură-te că fișierele sunt în această cale
    - assets/blockly/index.html
    - assets/blockly/custom_blocks.js
    - assets/blockly/custom_generator.js
    - assets/blockly/blockly_compressed.js
    - assets/blockly/blocks_compressed.js
    - assets/blockly/javascript_compressed.js
    - assets/blockly/toolbox.xml
